// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqSNJaC4A4VU7TfMZs8HHtUTfb9GrrjQ',
    appId: '1:728168922971:web:42de269c695e6c47aba47e',
    messagingSenderId: '728168922971',
    projectId: 'zeloo-5aac7',
    authDomain: 'zeloo-5aac7.firebaseapp.com',
    storageBucket: 'zeloo-5aac7.firebasestorage.app',
    measurementId: 'G-LW21TKZK31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIt-nyxcfu9ovHEETpny9QHuV4vK00ShQ',
    appId: '1:728168922971:android:56e440aed3c97c36aba47e',
    messagingSenderId: '728168922971',
    projectId: 'zeloo-5aac7',
    storageBucket: 'zeloo-5aac7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZeRKMS-LUAanjK0s1nP7mzjmfCLaErU',
    appId: '1:728168922971:ios:75c1978daddd9147aba47e',
    messagingSenderId: '728168922971',
    projectId: 'zeloo-5aac7',
    storageBucket: 'zeloo-5aac7.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoZeloo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZeRKMS-LUAanjK0s1nP7mzjmfCLaErU',
    appId: '1:728168922971:ios:75c1978daddd9147aba47e',
    messagingSenderId: '728168922971',
    projectId: 'zeloo-5aac7',
    storageBucket: 'zeloo-5aac7.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoZeloo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChqSNJaC4A4VU7TfMZs8HHtUTfb9GrrjQ',
    appId: '1:728168922971:web:ab9ef077bd617f9baba47e',
    messagingSenderId: '728168922971',
    projectId: 'zeloo-5aac7',
    authDomain: 'zeloo-5aac7.firebaseapp.com',
    storageBucket: 'zeloo-5aac7.firebasestorage.app',
    measurementId: 'G-0PFHBF2RWJ',
  );
}
