import 'package:flutter/material.dart';
import 'firebase_service.dart';

class PedidosScreen extends StatefulWidget { const PedidosScreen({super.key}); @override State<PedidosScreen> createState()=>_PedidosScreenState(); }
class _PedidosScreenState extends State<PedidosScreen>{
  static const _gradient=LinearGradient(colors:[Color(0xFF00C6D7),Color(0xFF0077B6)],begin:Alignment.topLeft,end:Alignment.bottomRight);
  String _filtro='Todos'; static const _filtros=['Todos','Aguardando','Confirmado','Concluído','Cancelado'];
  String _status(String f){switch(f){case'Aguardando':return'aguardando';case'Confirmado':return'confirmado';case'Concluído':return'concluido';case'Cancelado':return'cancelado';default:return'';}}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF4F7FB),body:StreamBuilder(stream:FirebaseService.meusPedidosCliente(),builder:(context,s){
    if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());
    if(s.hasError)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Text('Não foi possível carregar seus pedidos.\n${s.error}',textAlign:TextAlign.center)));
    final docs=s.data?.docs??[];final status=_status(_filtro);final pedidos=docs.where((d){final p=d.data();return status.isEmpty||p['status']==status;}).toList();
    return CustomScrollView(slivers:[
      SliverAppBar(expandedHeight:140,pinned:true,backgroundColor:Colors.transparent,elevation:0,automaticallyImplyLeading:false,flexibleSpace:FlexibleSpaceBar(background:Container(decoration:const BoxDecoration(gradient:_gradient,borderRadius:BorderRadius.only(bottomLeft:Radius.circular(32),bottomRight:Radius.circular(32))),padding:const EdgeInsets.fromLTRB(24,56,24,20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Meus Pedidos',style:TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('Acompanhe seus serviços',style:TextStyle(color:Colors.white70,fontSize:14))])))),
      SliverToBoxAdapter(child:SizedBox(height:54,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:20,vertical:10),itemCount:_filtros.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i){final f=_filtros[i];final sel=f==_filtro;return GestureDetector(onTap:()=>setState(()=>_filtro=f),child:Container(padding:const EdgeInsets.symmetric(horizontal:14,vertical:6),decoration:BoxDecoration(gradient:sel?_gradient:null,color:sel?null:Colors.white,borderRadius:BorderRadius.circular(20)),child:Text(f,style:TextStyle(fontSize:12,fontWeight:FontWeight.w700,color:sel?Colors.white:Colors.grey[600]))));}))),
      pedidos.isEmpty?const SliverFillRemaining(child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.receipt_long_rounded,size:64,color:Color(0xFFCCCCCC)),SizedBox(height:16),Text('Nenhum pedido encontrado.',style:TextStyle(color:Colors.grey,fontSize:15))]))):SliverPadding(padding:const EdgeInsets.fromLTRB(20,8,20,32),sliver:SliverList(delegate:SliverChildBuilderDelegate((context,i)=>_CardPedido(dados:pedidos[i].data()),childCount:pedidos.length))),
    ]);
  }));
}
class _CardPedido extends StatelessWidget{final Map<String,dynamic> dados;const _CardPedido({required this.dados});
  String t(dynamic v,[String d='Não informado'])=>v==null||v.toString().trim().isEmpty?d:v.toString();
  @override Widget build(BuildContext context){final status=t(dados['status'],'aguardando');const cfg={'aguardando':['Aguardando',0xFFFF9800],'confirmado':['Confirmado',0xFF0077B6],'concluido':['Concluído',0xFF4CAF50],'cancelado':['Cancelado',0xFFE53E3E]};final c=cfg[status]??cfg['aguardando']!;final cor=Color(c[1] as int);return Container(margin:const EdgeInsets.only(bottom:12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.06),blurRadius:12,offset:const Offset(0,3))]),child:Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:cor.withOpacity(.12),borderRadius:BorderRadius.circular(14)),child:Icon(Icons.receipt_long_rounded,color:cor)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t(dados['profissionalNome']),style:const TextStyle(fontWeight:FontWeight.w800,fontSize:14)),const SizedBox(height:3),Text(t(dados['servico']),style:TextStyle(fontSize:12,color:Colors.grey[500]))])),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:cor.withOpacity(.12),borderRadius:BorderRadius.circular(10)),child:Text(c[0] as String,style:TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:cor)))])),Divider(height:1,color:Colors.grey[100]),Padding(padding:const EdgeInsets.symmetric(horizontal:16,vertical:12),child:Row(children:[Icon(Icons.calendar_today_rounded,size:14,color:Colors.grey[400]),const SizedBox(width:5),Text('${t(dados['data'])} às ${t(dados['horario'])}',style:TextStyle(fontSize:12,color:Colors.grey[500])),const Spacer(),Text('R\$ ${t(dados['valor'],'0,00')}',style:const TextStyle(fontSize:14,fontWeight:FontWeight.w800,color:Color(0xFF0077B6)))]))]));}
}
