import 'package:flutter/material.dart';
import 'firebase_service.dart';

class PerfilEditarScreen extends StatefulWidget{const PerfilEditarScreen({super.key});@override State<PerfilEditarScreen> createState()=>_PerfilEditarState();}
class _PerfilEditarState extends State<PerfilEditarScreen>{final nome=TextEditingController(),email=TextEditingController(),telefone=TextEditingController();bool loading=true,salvando=false;
 @override void initState(){super.initState();_carregar();}
 Future<void> _carregar()async{final doc=await FirebaseService.dadosUsuario();if(doc!=null&&mounted){final d=doc.data()??{};nome.text=d['nome']?.toString()??'';email.text=d['email']?.toString()??FirebaseService.usuario?.email??'';telefone.text=d['telefone']?.toString()??'';}if(mounted)setState(()=>loading=false);}
 @override void dispose(){nome.dispose();email.dispose();telefone.dispose();super.dispose();}
 Future<void> _salvar()async{if(nome.text.trim().isEmpty){_erro('Informe seu nome.');return;}if(!RegExp(r'^\S+@\S+\.\S+$').hasMatch(email.text.trim())){_erro('Informe um e-mail válido.');return;}setState(()=>salvando=true);try{await FirebaseService.atualizarUsuario({'nome':nome.text.trim(),'email':email.text.trim(),'telefone':telefone.text.trim()});if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Perfil atualizado!')));Navigator.pop(context);}catch(e){if(mounted){setState(()=>salvando=false);_erro('Não foi possível salvar: $e');}}}
 void _erro(String m)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m),backgroundColor:const Color(0xFFE53E3E)));
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final ini=nome.text.trim().split(' ').where((x)=>x.isNotEmpty).take(2).map((x)=>x[0].toUpperCase()).join();return Scaffold(backgroundColor:const Color(0xFFF4F7FB),appBar:AppBar(title:const Text('Editar Perfil'),backgroundColor:const Color(0xFF0077B6),foregroundColor:Colors.white),body:ListView(padding:const EdgeInsets.all(24),children:[Center(child:CircleAvatar(radius:48,backgroundColor:const Color(0xFF0077B6),child:Text(ini,style:const TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w800)))),const SizedBox(height:32),_Campo('Nome Completo',nome),const SizedBox(height:20),_Campo('Email',email,TextInputType.emailAddress),const SizedBox(height:20),_Campo('Telefone',telefone,TextInputType.phone),const SizedBox(height:36),SizedBox(height:52,child:ElevatedButton(onPressed:salvando?null:_salvar,style:ElevatedButton.styleFrom(backgroundColor:const Color(0xFF0077B6)),child:salvando?const CircularProgressIndicator(color:Colors.white):const Text('Salvar alterações',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w700))))]));}
}
class _Campo extends StatelessWidget{final String label;final TextEditingController controller;final TextInputType tipo;const _Campo(this.label,this.controller,[this.tipo=TextInputType.text]);@override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(fontWeight:FontWeight.w600)),const SizedBox(height:8),TextField(controller:controller,keyboardType:tipo,decoration:InputDecoration(filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none))) ]);}
